In [ ]:
print("Doing Data Analysis")

Doing Data Analysis

In [ ]:
#importing Library
import pandas as pd

In [ ]:
#loading dataset
df=pd.read_csv("/content/diabetes.csv")

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.head()
#see first 5 records

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.head(10)
#see first 10 records

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [ ]:
df.tail()
#see last five records

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.info()
#column name and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()
#

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:

df.Age

0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age, Length: 768, dtype: int64

In [ ]:
df[['Glucose','BloodPressure','SkinThickness']]

     Glucose  BloodPressure  SkinThickness
0        148             72             35
1         85             66             29
2        183             64              0
3         89             66             23
4        137             40             35
..       ...            ...            ...
763      101             76             48
764      122             70             27
765      121             72             23
766      126             60              0
767       93             70             31

[768 rows x 3 columns]

In [ ]:
#sum the null value of each column
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df1=pd.read_csv("/content/diabetes 1.csv")

In [ ]:
df1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,0.0,NaN,0.315,23,0

In [ ]:
df1.isnull().sum()

Pregnancies                 0
Glucose                     1
BloodPressure               4
SkinThickness               1
Insulin                     3
BMI                         6
DiabetesPedigreeFunction    1
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df1.isnull().sum()

Pregnancies                 0
Glucose                     1
BloodPressure               4
SkinThickness               1
Insulin                     3
BMI                         6
DiabetesPedigreeFunction    1
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.Age.mean()

np.float64(33.240885416666664)

In [ ]:
#fill the null value of age using mean
df1['Age']=df1['Age'].fillna(df1.Age.mean())

In [ ]:
df1.isnull().sum()

Pregnancies                 0
Glucose                     1
BloodPressure               4
SkinThickness               1
Insulin                     3
BMI                         6
DiabetesPedigreeFunction    1
Age                         0
Outcome                     0
dtype: int64

In [ ]:
#cheak the duplicate values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#to count unique values for column
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [ ]:
#check the invalid zero values(real missing data)
 (df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0)

     Glucose  BloodPressure  SkinThickness  Insulin    BMI
0      False          False          False     True  False
1      False          False          False     True  False
2      False          False           True     True  False
3      False          False          False    False  False
4      False          False          False    False  False
..       ...            ...            ...      ...    ...
763    False          False          False    False  False
764    False          False          False     True  False
765    False          False          False    False  False
766    False          False           True     True  False
767    False          False          False     True  False

[768 rows x 5 columns]

In [ ]:
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0).sum()

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

In [ ]:
df['BloodPressure']

0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64

In [ ]:
#filter row by some condition
df[df['Age']>60]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
115,4,146,92,0,0,31.2,0.539,61,1
123,5,132,80,0,0,26.8,0.186,69,0
129,0,105,84,0,0,27.9,0.741,62,1
148,5,147,78,0,0,33.7,0.218,65,0
221,2,158,90,0,0,31.6,0.805,66,1
223,7,142,60,33,190,28.8,0.687,61,0
263,3,142,80,15,0,32.4,0.200,63,0
294,0,161,50,0,0,21.9,0.254,65,0
361,5,158,70,0,0,29.8,0.207,63,0
362,5,103,108,37,0,39.2,0.305,65,0
363,4,146,78,0,0,38.5,0.520,67,1
453,2,119,0,0,0,19.6,0.832,72,0
456,1,135,54,0,0,26.7,0.687,62,0
459,9,134,74,33,60,25.9,0.460,81,0
479,4,132,86,31,0,28.0,0.419,63,0
489,8,194,80,0,0,26.1,0.551,67,0
495,6,166,74,0,0,26.6,0.304,66,0
509,8,120,78,0,0,25.0,0.409,64,0
537,0,57,60,0,0,21.7,0.735,67,0
552,6,114,88,0,0,27.8,0.247,66,0
579,2,197,70,99,0,34.7,0.575,62,1
582,12,121,78,17,0,26.5,0.259,62,0
666,4,145,82,18,0,32.5,0.235,70,1
674,8,91,82,0,0,35.6,0.587,68,0
684,5,136,82,0,0,0.0,0.640,69,0
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [ ]:

df[(df['Age']>65)&(df['BMI']>30)==0]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df[(df['Age']>65)&(df['Outcome'])==1]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
221,2,158,90,0,0,31.6,0.805,66,1
363,4,146,78,0,0,38.5,0.520,67,1
666,4,145,82,18,0,32.5,0.235,70,1
759,6,190,92,0,0,35.5,0.278,66,1

In [ ]:
#Access rows by index

df.iloc[700:710]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
700,2,122,76,27,200,35.9,0.483,26,0
701,6,125,78,31,0,27.6,0.565,49,1
702,1,168,88,29,0,35.0,0.905,52,1
703,2,129,0,0,0,38.5,0.304,41,0
704,4,110,76,20,100,28.4,0.118,27,0
705,6,80,80,36,0,39.8,0.177,28,0
706,10,115,0,0,0,0.0,0.261,30,1
707,2,127,46,21,335,34.4,0.176,22,0
708,9,164,78,0,0,32.8,0.148,45,1
709,2,93,64,32,160,38.0,0.674,23,1

In [ ]:
#the loc function is lable based data selecting method which means that we have to pass the name of the row and the column which we want to select
df1.loc[0:4,['BMI','Age']]

    BMI  Age
0  33.6   50
1  26.6   31
2  23.3   32
3  28.1   21
4  43.1   33

In [ ]:
#short by using by column
df.sort_values(by='Age')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
736,0,126,86,27,120,27.4,0.515,21,0
738,2,99,60,17,160,36.6,0.453,21,0
721,1,114,66,36,200,38.1,0.289,21,0
60,2,84,0,0,0,0.0,0.304,21,0
290,0,78,88,29,40,36.9,0.434,21,0
...,...,...,...,...,...,...,...,...,...
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
666,4,145,82,18,0,32.5,0.235,70,1
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0

In [ ]:
df1['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:

df.groupby('Outcome').agg('mean')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
#statistics
#mean of a column
df['BMI'].mean()

np.float64(31.992578124999998)

In [ ]:
#coorelation matric
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000